### ISSUE TITLE
Cannot return null for non-nullable field EventSource.Abi

### ISSUE THREAD

**Issue by tkiapril** [planetarium/Corvette#14] opened 2023-07-19 09:02 UTC
```
error: Uncaught Error: 
Invalid `prisma.eventSource.findMany()` invocation:


Cannot return null for non-nullable field EventSource.Abi.
    at vo.handleRequestError (file:///Users/tki/RiderProjects/Corvette/generated/client/runtime/edge-esm.js:85:7470)
    at vo.handleAndLogRequestError (file:///Users/tki/RiderProjects/Corvette/generated/client/runtime/edge-esm.js:85:6622)
    at vo.request (file:///Users/tki/RiderProjects/Corvette/generated/client/runtime/edge-esm.js:85:6501)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async CreateWatch (file:///Users/tki/RiderProjects/Corvette/observer.ts:60:13)
    at async Object.handler (file:///Users/tki/RiderProjects/Corvette/observer.ts:52:25)
```

Reproduction steps:
1. deno task prisma generate --data-proxy
2. deno task prisma db push
3. deno task serve
4. cd web; deno task start
5. Add contents of `sample/contract/sampleAbi.json` to Abi.
6. Add EventSource pairs `0x17ec6f0ad5e7b141f7d750bfc3f8639b7a85e377` `0x0b291f5ed3dd7dd8fbb5bf2bfe7cc6b1c0910ee877caab99b6db1c95e107073c` & `0x17ec6f0ad5e7b141f7d750bfc3f8639b7a85e377` `0x174ad6f40a94f5d83762a22463485159a77e605aac63e75b0eb2c2d634771f39`
7. `await prisma.eventSource.findMany({select: { abiHash: true, address: true, Abi: { select: { json: true } } }, })` throws upon reload, following adding second pair

**Comment by eseiker** [comment] 2023-08-19 06:17
this issue was caused by dataproxy, fixed by #62

**Closed by eseiker** 2023-08-19 06:17 UTC
Labels: help wanted
